// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBicL7-6pTrlZvy1rZf9WKbcExQJITZSDc',
    appId: '1:108279766799:web:14bf29035aaf5d242b687a',
    messagingSenderId: '108279766799',
    projectId: 'nextflutter-102d8',
    authDomain: 'nextflutter-102d8.firebaseapp.com',
    storageBucket: 'nextflutter-102d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB59BAtmH__K4TcA9Lw14sqd35nCJBeNNk',
    appId: '1:108279766799:android:063ddc8b8965449e2b687a',
    messagingSenderId: '108279766799',
    projectId: 'nextflutter-102d8',
    storageBucket: 'nextflutter-102d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjj2j6vP23uuBA-FRRuO5LUmW2K5zf3sg',
    appId: '1:108279766799:ios:130ef7f41f0eb6e92b687a',
    messagingSenderId: '108279766799',
    projectId: 'nextflutter-102d8',
    storageBucket: 'nextflutter-102d8.firebasestorage.app',
    iosBundleId: 'com.example.appflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjj2j6vP23uuBA-FRRuO5LUmW2K5zf3sg',
    appId: '1:108279766799:ios:130ef7f41f0eb6e92b687a',
    messagingSenderId: '108279766799',
    projectId: 'nextflutter-102d8',
    storageBucket: 'nextflutter-102d8.firebasestorage.app',
    iosBundleId: 'com.example.appflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBicL7-6pTrlZvy1rZf9WKbcExQJITZSDc',
    appId: '1:108279766799:web:1a8bf96d1d63cc3d2b687a',
    messagingSenderId: '108279766799',
    projectId: 'nextflutter-102d8',
    authDomain: 'nextflutter-102d8.firebaseapp.com',
    storageBucket: 'nextflutter-102d8.firebasestorage.app',
  );
}
